import pygame
import time
pygame.mixer.pre_init(22050, -16, 1, 256)
pygame.mixer.init()
sound1 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down1.wav")
sound2 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down2.wav")
sound3 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down3.wav")
sound4 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down4.wav")
sound5 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down5.wav")
sound6 = pygame.mixer.Sound("sp_cmxb/alpha/down/alpha_down6.wav")
sound1.play()
time.sleep(.1)
sound2.play()
time.sleep(.1)
sound3.play()
time.sleep(.1)
sound4.play()
time.sleep(5)